{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "c005dc2c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ipython-sql in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: sqlalchemy in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (2.0.41)\n",
      "Requirement already satisfied: prettytable in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython-sql) (3.16.0)\n",
      "Requirement already satisfied: ipython in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython-sql) (9.4.0)\n",
      "Requirement already satisfied: sqlparse in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython-sql) (0.5.3)\n",
      "Requirement already satisfied: six in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython-sql) (1.17.0)\n",
      "Requirement already satisfied: ipython-genutils in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: greenlet>=1 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from sqlalchemy) (3.2.3)\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from sqlalchemy) (4.14.1)\n",
      "Requirement already satisfied: colorama in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (0.4.6)\n",
      "Requirement already satisfied: decorator in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (5.2.1)\n",
      "Requirement already satisfied: ipython-pygments-lexers in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (1.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (0.19.2)\n",
      "Requirement already satisfied: matplotlib-inline in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (0.1.7)\n",
      "Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (3.0.51)\n",
      "Requirement already satisfied: pygments>=2.4.0 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (2.19.2)\n",
      "Requirement already satisfied: stack_data in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (0.6.3)\n",
      "Requirement already satisfied: traitlets>=5.13.0 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from ipython->ipython-sql) (5.14.3)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.13)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)\n",
      "Requirement already satisfied: executing>=1.2.0 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from stack_data->ipython->ipython-sql) (2.2.0)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from stack_data->ipython->ipython-sql) (3.0.0)\n",
      "Requirement already satisfied: pure-eval in c:\\users\\tutas\\documents\\projetos github\\projeto-analisevendasloja\\.venv\\lib\\site-packages (from stack_data->ipython->ipython-sql) (0.2.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install ipython-sql sqlalchemy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5f63b772",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'classes'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mclasses\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mclassdatabasemanager\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m DatabaseManager\n\u001b[0;32m      2\u001b[0m \u001b[38;5;66;03m# Conecta automaticamente\u001b[39;00m\n\u001b[0;32m      3\u001b[0m db_manager \u001b[38;5;241m=\u001b[39m DatabaseManager()\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'classes'"
     ]
    }
   ],
   "source": [
    "\n",
    "from classes.classdatabasemanager import DatabaseManager\n",
    "# Conecta automaticamente\n",
    "db_manager = DatabaseManager()\n",
    "\n",
    "# Executa SQL\n",
    "query = \"SELECT * FROM vendas LIMIT 5;\"\n",
    "resultado = db_manager.fetch_data_to_df(query)\n",
    "\n",
    "# Mostra resultados\n",
    "display(resultado)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61b3c4e3",
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fcb5bc6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3297, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1264, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 713, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 675, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 901, in __connect\n",
      "    with util.safe_reraise():\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 897, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 646, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 625, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "sqlite3.OperationalError: unable to open database file\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sql\\connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "                               ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3273, in connect\n",
      "    return self._connection_cls(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 147, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2436, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3297, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1264, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 713, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 675, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 901, in __connect\n",
      "    with util.safe_reraise():\n",
      "         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 224, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 897, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 646, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\tutas\\Documents\\Projetos GitHUB\\projeto-analisevendasloja\\.venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 625, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql sqlite:///database/loja.db"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
